name: Extract Boot Image

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'INPUT URL LINK DOWNLOAD'
        required: true
        type: string

jobs:
  extract-boot-img:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Environment
      run: sudo apt-get update && sudo apt-get install -y unzip tar xz-utils

    - name: Download Stock ROM
      # Replace with your actual ROM URL or path in the repo
      run: wget -O stock_rom.tgz "${{ github.event.inputs.rom_url }}"

    - name: Extract Boot Image
      run: |
        mkdir extracted_rom
        tar -xvzf stock_rom.tgz -C extracted_rom
        ls -lh extracted_rom
    
    - name: find file
      run: |
        find extracted_rom -name "boot.img" -exec cp {} . \;
        find extracted_rom -name "vbmeta.img" -exec cp {} . \;

    - name: Upload Boot Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot_vbmeta_images
        path: |
          boot.img
          vbmeta.img
        
